AWSTemplateFormatVersion: 2010-09-09
Description: >-
  twitter-unfollower-alerts

Transform:
- AWS::Serverless-2016-10-31

Resources:
  UnfollowAlerter:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: src/handlers/unfollower-alerter.handler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      MemorySize: 128
      Timeout: 100

  Followers:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: followers
      PrimaryKey:
       Name: userId
       Type: String
